server:
  port: 8088
  context-path: /blog
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
mybatis:
  config-location: classpath:sqlmap/sqlmap-config.xml